import type { CaseStudyProps } from '../components/case-study'

/**
 * Australian Labour Market case study.
 *
 * Copy lifted from the previous page and kept in the author's voice, per
 * Section 11.C. The only systematic change is that all 27 em-dashes are gone,
 * rewritten into sentences, commas or colons rather than swapped for a
 * different dash.
 */
export const labourMarket: CaseStudyProps = {
  kicker: 'Data pipeline',
  hookLead: 'Four in five working men are full-time.',
  hookTail: 'For women it is barely one in two.',
  sub: 'An end-to-end analytics pipeline on live Australian Bureau of Statistics data. Python ingests it, Azure SQL models it, and a four-page Power BI report visualises it. The whole report is generated as code rather than clicked together by hand.',
  meta: [
    ['Role', 'Solo build'],
    ['Stack', 'Python, Azure SQL, Power BI'],
    ['Source', 'ABS Data API, live'],
    ['Window', '1978 to 2026'],
  ],
  contents: [
    ['overview', 'Overview'],
    ['source', 'The data'],
    ['build', 'The build'],
    ['findings', 'What the data says'],
    ['next', 'What is next'],
  ],
  links: [
    { label: 'Source and build script', href: 'https://github.com/MelvinDY/aus_job_dashboard', primary: true },
    { label: 'Dashboard PDF', href: '/projects/labour-market/aus-labour-dashboard.pdf' },
    { label: 'ABS data source', href: 'https://www.abs.gov.au/statistics/labour' },
  ],
  nextStudy: { href: '/projects/data/youtube', title: 'YouTube Trending Analytics' },
  blocks: [
    { t: 'h', id: 'overview', text: 'Overview' },
    { t: 'p', text: 'Every politician has a line about jobs. I wanted the number behind the line: not the headline rate, but the shape of who is working, in what, full-time or part, and how that has shifted.' },
    { t: 'p', text: 'So I built the whole stack an analyst actually uses. Python pulls the ABS Labour Force series straight off the API, pandas cleans and reshapes it, Azure SQL stores and models it through a layered view pattern, and Power BI sits on top as a four-page report covering the national picture, the states, industries, and the full-time to part-time split.' },
    { t: 'p', text: 'This page is that report told as a story: the strongest findings first, the engineering that makes them trustworthy underneath.' },
    {
      t: 'stats',
      items: [
        { figure: '4.49%', caption: 'National unemployment rate, near historic lows.' },
        { figure: '14.7M', caption: 'Employed persons, a record high of 14,737k.' },
        { figure: '66.71%', caption: 'Participation rate, also near record territory.' },
      ],
    },

    { t: 'h', id: 'source', text: 'The data' },
    { t: 'p', text: 'Everything here comes from the Australian Bureau of Statistics, the same Labour Force survey the RBA and Treasury quote. I hit the ABS Data API directly, no key required: the monthly Labour Force series for the national, state and full-time to part-time numbers, and the annual Labour Account for employment by industry. The national series runs back to February 1978 and is current to early 2026.' },

    { t: 'h', id: 'build', text: 'The build' },
    { t: 'p', text: 'The pipeline is deliberately boring, which is the point. The raw ABS output is messy multi-dimension data with coded labels and a wide shape. I parse the time periods, map the dimension codes to readable names, and reshape it long. The cleaned data lands in Azure SQL staging tables, then a staging to mart view layer shapes the metrics. Power BI only ever reads the curated mart views, never the raw tables.' },
    { t: 'p', text: 'The Power BI report itself is generated by a Python script rather than hand-built in Desktop. One build_report.py writes the data model, every visual, the 15 DAX measures and a custom colour theme as text files. So the entire dashboard is diff-able, reviewable and version-controlled like code. If it ever corrupts I regenerate it instead of fighting a binary .pbix.' },
    { t: 'p', text: 'It runs on serverless Azure SQL, which auto-pauses when idle. The whole thing costs roughly $2 to $6 a month, almost all of it storage rather than compute.' },
    {
      t: 'flow',
      items: [
        { stage: 'Ingest', tool: 'ABS Data API', what: 'Python, live pull, no key' },
        { stage: 'Transform', tool: 'pandas', what: 'clean, map codes, reshape' },
        { stage: 'Store and model', tool: 'Azure SQL', what: 'staging to mart views, T-SQL' },
        { stage: 'Visualise', tool: 'Power BI', what: 'generated as code, DAX' },
      ],
    },
    {
      t: 'fig',
      src: '/projects/labour-market/pbi-overview.png',
      page: 'Page 1, Overview',
      alt: 'Power BI Overview page: national unemployment rate trend back to 1978, employed persons trend, and KPI cards for unemployment rate, employment, participation and employment-to-population ratio.',
      caption: 'The national headline series, seasonally adjusted. Unemployment at 4.49%, employment at a record 14.7M, up 0.88% year on year.',
    },

    { t: 'h', id: 'findings', text: 'What the data says' },
    { t: 'lede', text: 'Full-time work is not shared evenly. The part-time economy is overwhelmingly female.' },
    {
      t: 'bars',
      title: 'Full-time share of employment, by sex',
      unit: '% of jobs that are full-time',
      bars: [
        { label: 'Male', value: '79.98%', pct: 100, lead: true },
        { label: 'Persons', value: '68.95%', pct: 86 },
        { label: 'Female', value: '56.92%', pct: 71 },
      ],
      read: '80% of working men hold a full-time job. For women it is 57%. The gap has narrowed over decades but it is still a 23-point spread.',
    },
    {
      t: 'fig',
      src: '/projects/labour-market/pbi-ftpt.png',
      page: 'Page 4, Full-time vs Part-time',
      alt: 'Power BI Full-time vs Part-time page: stacked area of full-time against part-time employment, full-time share KPIs, full-time share by sex over time, and an employment-by-sex donut.',
      caption: 'Full-time is 68.95% of all jobs, up 0.19 ppt year on year. The by-sex lines tell the real story: male and female full-time shares have been drifting apart and back for forty years.',
    },

    { t: 'lede', text: 'The labour market is tight almost everywhere. The states barely differ.' },
    { t: 'p', text: 'I expected wide regional gaps. Instead the spread between the highest and lowest state unemployment rate is under 0.9 of a percentage point. Tasmania at the top, Western Australia at the bottom, everyone bunched in between.' },
    {
      t: 'bars',
      title: 'Unemployment rate by state, latest month',
      unit: '%, seasonally adjusted',
      bars: [
        { label: 'Tasmania', value: '4.99%', pct: 100, lead: true },
        { label: 'Victoria', value: '4.82%', pct: 97 },
        { label: 'New South Wales', value: '4.44%', pct: 89 },
        { label: 'Queensland', value: '4.27%', pct: 86 },
        { label: 'South Australia', value: '4.19%', pct: 84 },
        { label: 'Western Australia', value: '4.12%', pct: 83 },
      ],
      read: 'A 0.87 ppt spread across the states.',
    },
    { t: 'note', text: 'The ABS feed returned 6 of 8 jurisdictions. ACT and NT were missing at source, so I left them off rather than draw a map with holes in it.' },
    {
      t: 'fig',
      src: '/projects/labour-market/pbi-state.png',
      page: 'Page 2, State Breakdown',
      alt: 'Power BI State Breakdown page: ranked bars of unemployment rate and employed persons by state, plus an unemployment-rate trend line per state.',
      caption: 'Ranked bars instead of a map. A built-in Bing map rendered as a zoomed-out world view and read as broken, so I dropped it for bars that never look broken.',
    },

    { t: 'lede', text: 'Health care is the country’s biggest employer, and this is where I have to be honest about the data.' },
    { t: 'p', text: 'By headcount, Health Care and Social Assistance and Retail Trade sit at the top of the industry table. But the industry breakdown comes from the annual ABS Labour Account, which lags badly: it ends at 2022, while everything else on the dashboard is current.' },
    { t: 'note', text: 'I confirmed via the live API that the industry series is stale at source. Rather than quietly mix a 2022 series with current numbers, every industry title carries its own vintage. Knowing a source’s recency before you build on it matters more than any chart.' },
    {
      t: 'fig',
      src: '/projects/labour-market/pbi-industry.png',
      page: 'Page 3, Industry View',
      alt: 'Power BI Industry View page: horizontal bar of employed persons across 19 ANZSIC divisions for 2022, a focus-industries trend line, and an industry detail table with year-on-year growth.',
      caption: 'All 19 ANZSIC divisions ranked by employment, with a growing and shrinking detail table. Titles say "2022, annual" on purpose, because the source ends there.',
    },

    { t: 'pull', text: 'The headline rate hides the composition. Who works full-time, and where, is the part that actually moved.' },

    { t: 'h', id: 'next', text: 'What is next' },
    {
      t: 'list',
      items: [
        'Replace the stale annual industry source with a current quarterly Labour Force Detailed employed-by-industry series, so every page is current to the same month.',
        'Fix the missing ACT and NT in the state mart view by chasing the gap back through staging to mart filtering.',
        'Harden the Azure side: a budget and cost alert, secrets in Key Vault, and Azure AD auth to the SQL database instead of a SQL login.',
      ],
    },
  ],
}
